# 1. Port settings (Render ke liye 10000 zaroori hai)
server.port=${PORT:8080}
server.address=0.0.0.0

# 2. Database variables (Naam wahi rakhein jo Render Environment mein hain)
spring.datasource.url=${MY_DB_URL}
spring.datasource.username=${MY_DB_USERNAME}
spring.datasource.password=${MY_DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# 3. JPA & Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Hibernate automatically detects the dialect, so you can remove the old line
# ya phir niche wala use karein:
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Optional: To suppress the OSIV warning from your logs
spring.jpa.open-in-view=false